In [1]:
import sqlite3
import pandas as pd
from IPython.display import display

con = sqlite3.connect("books.db")
pd.set_option("display.width", 200)
pd.set_option("display.max_colwidth", 60)

def run(label, sql):
    print("\n" + "=" * 78)
    print(label)
    print("-" * 78)
    print(sql.strip())
    df = pd.read_sql_query(sql, con)
    display(df)
    return df

In [2]:
q1 = """
SELECT title, price_gbp, rating
FROM books
WHERE rating = 5 AND in_stock = 1
ORDER BY price_gbp DESC;
"""
df1 = run("Q1 — SELECT / WHERE (5-star, in stock)", q1)

==============================================================================
Q1 — SELECT / WHERE (5-star, in stock)
------------------------------------------------------------------------------
SELECT title, price_gbp, rating
FROM books
WHERE rating = 5 AND in_stock = 1
ORDER BY price_gbp DESC;

                                                          title  price_gbp  rating
0                                                      El Deafo      57.62       5
1   The Sandman, Vol. 3: Dream Country (The Sandman (volumes...      55.55       5
2                       A Flight of Arrows (The Pathfinders #2)      55.53       5
3   The Bachelor Girl's Guide to Murder (Herringford and Wat...      52.30       5
4       Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)      52.29       5
5                        A Time of Torment (Charlie Parker #14)      48.35       5
6   Rat Queens, Vol. 1: Sass & Sorcery (Rat Queens (Collecte...      46.96       5
7                                           While You Were Mine      41.32       5
8                      Fruits Basket, Vol. 1 (Fruits Basket #1)      40.28       5
9                                                  The Red Tent      35.66       5
10  Bleach, Vol. 1: Strawberry and the Soul Reapers (Bleach #1)      34.65       5
11                                                 Mrs. Houdini      30.25       5
12                                        The Passion of Dolssa      28.32       5
13                           1,000 Places to See Before You Die      26.08       5
14  What Happened on Beale Street (Secrets of the South Myst...      25.37       5
15                            The Silkworm (Cormoran Strike #2)      23.05       5
16                Saga, Volume 3 (Saga (Collected Editions) #3)      21.57       5
17                                       Voyager (Outlander #3)      21.07       5
18                                       Between Shades of Gray      20.79       5
19            A Spy's Devotion (The Regency Spies of London #1)      16.97       5
20                     Batman: The Dark Knight Returns (Batman)      15.38       5
21                                                  Roller Girl      14.10       5
22  Princess Jellyfish 2-in-1 Omnibus, Vol. 01 (Princess Jel...      13.61       5
23                                            The Girl You Lost      12.29       5
24  Superman Vol. 1: Before Truth (Superman by Gene Luen Yan...      11.89       5
25                     Fruits Basket, Vol. 2 (Fruits Basket #2)      11.64       5

In [3]:
q2 = """
SELECT title, rating, price_inr
FROM books
ORDER BY rating DESC, price_inr DESC
LIMIT 10;
"""
df2 = run("Q2 — ORDER BY + LIMIT (top-10 by rating, then price)", q2)

==============================================================================
Q2 — ORDER BY + LIMIT (top-10 by rating, then price)
------------------------------------------------------------------------------
SELECT title, rating, price_inr
FROM books
ORDER BY rating DESC, price_inr DESC
LIMIT 10;

                                                         title  rating  price_inr
0                                                     El Deafo       5    6078.91
1  The Sandman, Vol. 3: Dream Country (The Sandman (volumes...       5    5860.52
2                      A Flight of Arrows (The Pathfinders #2)       5    5858.42
3  The Bachelor Girl's Guide to Murder (Herringford and Wat...       5    5517.65
4      Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)       5    5516.60
5                       A Time of Torment (Charlie Parker #14)       5    5100.92
6  Rat Queens, Vol. 1: Sass & Sorcery (Rat Queens (Collecte...       5    4954.28
7                                          While You Were Mine       5    4359.26
8                     Fruits Basket, Vol. 1 (Fruits Basket #1)       5    4249.54
9                                                 The Red Tent       5    3762.13

In [4]:
q3 = """
SELECT DISTINCT rating
FROM books
ORDER BY rating;
"""
df3 = run("Q3 — DISTINCT ratings present", q3)

==============================================================================
Q3 — DISTINCT ratings present
------------------------------------------------------------------------------
SELECT DISTINCT rating
FROM books
ORDER BY rating;

   rating
0       1
1       2
2       3
3       4
4       5

In [5]:
q4 = """
SELECT title, rating, price_gbp
FROM books
WHERE rating IN (4, 5)
  AND price_gbp BETWEEN 10 AND 30
ORDER BY price_gbp;
"""
df4 = run("Q4 — IN + BETWEEN (4–5 stars, £10–£30)", q4)

==============================================================================
Q4 — IN + BETWEEN (4–5 stars, £10–£30)
------------------------------------------------------------------------------
SELECT title, rating, price_gbp
FROM books
WHERE rating IN (4, 5)
  AND price_gbp BETWEEN 10 AND 30
ORDER BY price_gbp;

                                                          title  rating  price_gbp
0                      Fruits Basket, Vol. 2 (Fruits Basket #2)       5      11.64
1   Superman Vol. 1: Before Truth (Superman by Gene Luen Yan...       5      11.89
2                                             The Girl You Lost       5      12.29
3   Princess Jellyfish 2-in-1 Omnibus, Vol. 01 (Princess Jel...       5      13.61
4                                                   Roller Girl       5      14.10
5                                             The Secret Garden       4      15.08
6                      Batman: The Dark Knight Returns (Batman)       5      15.38
7        Outcast, Vol. 1: A Darkness Surrounds Him (Outcast #1)       4      15.44
8             A Spy's Devotion (The Regency Spies of London #1)       5      16.97
9                                                 Camp Midnight       4      17.08
10       Y: The Last Man, Vol. 1: Unmanned (Y: The Last Man #1)       4      18.51
11                                              This One Summer       4      19.49
12                                       Between Shades of Gray       5      20.79
13             Delivering the Truth (Quaker Midwife Mystery #1)       4      20.89
14                     Fruits Basket, Vol. 6 (Fruits Basket #6)       4      20.96
15                                       Voyager (Outlander #3)       5      21.07
16                Saga, Volume 3 (Saga (Collected Editions) #3)       5      21.57
17                       Paper Girls, Vol. 1 (Paper Girls #1-5)       4      21.71
18                            The Silkworm (Cormoran Strike #2)       5      23.05
19          The Mysterious Affair at Styles (Hercule Poirot #1)       4      24.80
20  What Happened on Beale Street (Secrets of the South Myst...       5      25.37
21                           1,000 Places to See Before You Die       5      26.08
22  The Complete Stories and Poems (The Works of Edgar Allan...       4      26.78
23                                        Lost Among the Living       4      27.70
24                               Little Women (Little Women #1)       4      28.07
25                                    The Marriage of Opposites       4      28.08
26                                        The Passion of Dolssa       5      28.32

In [6]:
q5 = """
SELECT c.category_name,
       b.title,
       b.rating,
       b.price_gbp,
       b.price_inr,
       b.in_stock
FROM books b
JOIN categories c ON b.category_id = c.category_id
WHERE b.rating >= 4
ORDER BY c.category_name, b.rating DESC, b.price_gbp DESC;
"""
df5 = run("Q5 — JOIN (4+ star books with category names)", q5)

==============================================================================
Q5 — JOIN (4+ star books with category names)
------------------------------------------------------------------------------
SELECT c.category_name,
       b.title,
       b.rating,
       b.price_gbp,
       b.price_inr,
       b.in_stock
FROM books b
JOIN categories c ON b.category_id = c.category_id
WHERE b.rating >= 4
ORDER BY c.category_name, b.rating DESC, b.price_gbp DESC;

         category_name                                                        title  rating  price_gbp  price_inr  in_stock
0             Classics                                    The Story of Hong Gildong       4      43.19    4556.54         1
1             Classics                               Little Women (Little Women #1)       4      28.07    2961.38         1
2             Classics  The Complete Stories and Poems (The Works of Edgar Allan...       4      26.78    2825.29         1
3             Classics                                            The Secret Garden       4      15.08    1590.94         1
4   Historical Fiction                      A Flight of Arrows (The Pathfinders #2)       5      55.53    5858.42         1
5   Historical Fiction                                          While You Were Mine       5      41.32    4359.26         1
6   Historical Fiction                                                 The Red Tent       5      35.66    3762.13         1
7   Historical Fiction                                                 Mrs. Houdini       5      30.25    3191.38         1
8   Historical Fiction                                        The Passion of Dolssa       5      28.32    2987.76         1
9   Historical Fiction                                       Voyager (Outlander #3)       5      21.07    2222.89         1
10  Historical Fiction                                       Between Shades of Gray       5      20.79    2193.34         1
11  Historical Fiction            A Spy's Devotion (The Regency Spies of London #1)       5      16.97    1790.33         1
12  Historical Fiction                                            A Paris Apartment       4      39.01    4115.55         1
13  Historical Fiction              World Without End (The Pillars of the Earth #2)       4      32.97    3478.34         1
14  Historical Fiction                                    The Marriage of Opposites       4      28.08    2962.44         1
15  Historical Fiction                                        Lost Among the Living       4      27.70    2922.35         1
16             Mystery  The Bachelor Girl's Guide to Murder (Herringford and Wat...       5      52.30    5517.65         1
17             Mystery                       A Time of Torment (Charlie Parker #14)       5      48.35    5100.92         1
18             Mystery  What Happened on Beale Street (Secrets of the South Myst...       5      25.37    2676.54         1
19             Mystery                            The Silkworm (Cormoran Strike #2)       5      23.05    2431.78         1
20             Mystery                                            The Girl You Lost       5      12.29    1296.59         1
21             Mystery  The No. 1 Ladies' Detective Agency (No. 1 Ladies' Detect...       4      57.70    6087.35         1
22             Mystery                                          The Past Never Ends       4      56.50    5960.75         1
23             Mystery        Murder at the 42nd Street Library (Raymond Ambler #1)       4      54.36    5734.98         1
24             Mystery                                                Sharp Objects       4      47.82    5045.01         1
25             Mystery              The Murder of Roger Ackroyd (Hercule Poirot #4)       4      44.10    4652.55         1
26             Mystery          The Mysterious Affair at Styles (Hercule Poirot #1)       4      24.80    2616.40         1
27             Mystery             Delivering the Truth (Quaker Midwife Mystery #1)       4      20.89    2203.90         1
28      Sequential Art                                                     El Deafo       5      57.62    6078.91         1
29      Sequential Art  The Sandman, Vol. 3: Dream Country (The Sandman (volumes...       5      55.55    5860.52         1
30      Sequential Art      Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)       5      52.29    5516.60         1
31      Sequential Art  Rat Queens, Vol. 1: Sass & Sorcery (Rat Queens (Collecte...       5      46.96    4954.28         1
32      Sequential Art                     Fruits Basket, Vol. 1 (Fruits Basket #1)       5      40.28    4249.54         1
33      Sequential Art  Bleach, Vol. 1: Strawberry and the Soul Reapers (Bleach #1)       5      34.65    3655.58         1
34      Sequential Art                Saga, Volume 3 (Saga (Collected Editions) #3)       5      21.57    2275.64         1
35      Sequential Art                     Batman: The Dark Knight Returns (Batman)       5      15.38    1622.59         1
36      Sequential Art                                                  Roller Girl       5      14.10    1487.55         1
37      Sequential Art  Princess Jellyfish 2-in-1 Omnibus, Vol. 01 (Princess Jel...       5      13.61    1435.86         1
38      Sequential Art  Superman Vol. 1: Before Truth (Superman by Gene Luen Yan...       5      11.89    1254.40         1
39      Sequential Art                     Fruits Basket, Vol. 2 (Fruits Basket #2)       5      11.64    1228.02         1
40      Sequential Art             Ajin: Demi-Human, Volume 1 (Ajin: Demi-Human #1)       4      57.06    6019.83         1
41      Sequential Art                         Giant Days, Vol. 1 (Giant Days #1-4)       4      56.76    5988.18         1
42      Sequential Art                                         Danganronpa Volume 1       4      51.99    5484.95         1
43      Sequential Art                     Fruits Basket, Vol. 4 (Fruits Basket #4)       4      50.44    5321.42         1
44      Sequential Art                 Fables, Vol. 1: Legends in Exile (Fables #1)       4      41.62    4390.91         1
45      Sequential Art    Ms. Marvel, Vol. 1: No Normal (Ms. Marvel (2014-2015) #1)       4      39.39    4155.65         1
46      Sequential Art                     The Nameless City (The Nameless City #1)       4      38.16    4025.88         1
47      Sequential Art  Wonder Woman: Earth One, Volume One (Wonder Woman: Earth...       4      37.34    3939.37         1
48      Sequential Art          Codename Baboushka, Volume 1: The Conclave of Death       4      36.72    3873.96         1
49      Sequential Art           So Cute It Hurts!!, Vol. 6 (So Cute It Hurts!! #6)       4      35.43    3737.86         1
50      Sequential Art                     Fruits Basket, Vol. 9 (Fruits Basket #9)       4      33.95    3581.73         1
51      Sequential Art                       Paper Girls, Vol. 1 (Paper Girls #1-5)       4      21.71    2290.41         1
52      Sequential Art                     Fruits Basket, Vol. 6 (Fruits Basket #6)       4      20.96    2211.28         1
53      Sequential Art                                              This One Summer       4      19.49    2056.19         1
54      Sequential Art       Y: The Last Man, Vol. 1: Unmanned (Y: The Last Man #1)       4      18.51    1952.80         1
55      Sequential Art                                                Camp Midnight       4      17.08    1801.94         1
56      Sequential Art       Outcast, Vol. 1: A Darkness Surrounds Him (Outcast #1)       4      15.44    1628.92         1
57              Travel                           1,000 Places to See Before You Die       5      26.08    2751.44         1
58              Travel                             A Year in Provence (Provence #1)       4      56.88    6000.84         1
59              Travel  Full Moon over Noahâs Ark: An Odyssey to Mount Ararat ...       4      49.43    5214.86         1

In [7]:
df_q2_sql = pd.read_sql(
    "SELECT title, rating, price_inr FROM books "
    "ORDER BY rating DESC, price_inr DESC LIMIT 10;", con
)
df_q5_sql = pd.read_sql(q5, con)     # the JOIN query from Cell 7

print("Q2 via pd.read_sql:")
display(df_q2_sql)
print("\nQ5 via pd.read_sql (the JOIN, first 10 rows):")
display(df_q5_sql.head(10))

Q2 via pd.read_sql:

                                                         title  rating  price_inr
0                                                     El Deafo       5    6078.91
1  The Sandman, Vol. 3: Dream Country (The Sandman (volumes...       5    5860.52
2                      A Flight of Arrows (The Pathfinders #2)       5    5858.42
3  The Bachelor Girl's Guide to Murder (Herringford and Wat...       5    5517.65
4      Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)       5    5516.60
5                       A Time of Torment (Charlie Parker #14)       5    5100.92
6  Rat Queens, Vol. 1: Sass & Sorcery (Rat Queens (Collecte...       5    4954.28
7                                          While You Were Mine       5    4359.26
8                     Fruits Basket, Vol. 1 (Fruits Basket #1)       5    4249.54
9                                                 The Red Tent       5    3762.13

Q5 via pd.read_sql (the JOIN, first 10 rows):

        category_name                                                        title  rating  price_gbp  price_inr  in_stock
0            Classics                                    The Story of Hong Gildong       4      43.19    4556.54         1
1            Classics                               Little Women (Little Women #1)       4      28.07    2961.38         1
2            Classics  The Complete Stories and Poems (The Works of Edgar Allan...       4      26.78    2825.29         1
3            Classics                                            The Secret Garden       4      15.08    1590.94         1
4  Historical Fiction                      A Flight of Arrows (The Pathfinders #2)       5      55.53    5858.42         1
5  Historical Fiction                                          While You Were Mine       5      41.32    4359.26         1
6  Historical Fiction                                                 The Red Tent       5      35.66    3762.13         1
7  Historical Fiction                                                 Mrs. Houdini       5      30.25    3191.38         1
8  Historical Fiction                                        The Passion of Dolssa       5      28.32    2987.76         1
9  Historical Fiction                                       Voyager (Outlander #3)       5      21.07    2222.89         1

In [8]:
books_df = pd.read_sql("SELECT * FROM books;", con)
cats_df  = pd.read_sql("SELECT * FROM categories;", con)
con.close()
print("books_df:", books_df.shape, " cats_df:", cats_df.shape)

books_df: (163, 7)  cats_df: (5, 2)

In [9]:
merged = (books_df.merge(cats_df, on="category_id", how="inner")
                   .query("rating >= 4")
                   .sort_values(["category_name", "rating", "price_gbp"],
                                ascending=[True, False, False])
                   .reset_index(drop=True))

sql_join = df_q5_sql.reset_index(drop=True)
print("pd.merge result (first 10 rows):")
display(merged.head(10))

pd.merge result (first 10 rows):

   book_id                                                        title  price_gbp  price_inr  rating  in_stock  category_id       category_name
0      158                                    The Story of Hong Gildong      43.19    4556.54       4         1            1            Classics
1      149                               Little Women (Little Women #1)      28.07    2961.38       4         1            1            Classics
2      155  The Complete Stories and Poems (The Works of Edgar Allan...      26.78    2825.29       4         1            1            Classics
3      145                                            The Secret Garden      15.08    1590.94       4         1            1            Classics
4       46                      A Flight of Arrows (The Pathfinders #2)      55.53    5858.42       5         1            2  Historical Fiction
5       65                                          While You Were Mine      41.32    4359.26       5         1            2  Historical Fiction
6       60                                                 The Red Tent      35.66    3762.13       5         1            2  Historical Fiction
7       48                                                 Mrs. Houdini      30.25    3191.38       5         1            2  Historical Fiction
8       57                                        The Passion of Dolssa      28.32    2987.76       5         1            2  Historical Fiction
9       59                                       Voyager (Outlander #3)      21.07    2222.89       5         1            2  Historical Fiction

In [10]:
print("=" * 78)
print("SQL JOIN vs pd.merge — side by side")
print("=" * 78)

print("\nSQL JOIN result (first 10):")
display(sql_join.head(10))

print("\npd.merge result (first 10):")
display(merged.head(10))

cols = ["category_name", "title", "rating", "price_gbp", "price_inr", "in_stock"]
equivalent = sql_join[cols].equals(merged[cols])
print(f"\nEquivalent (same columns, same order, same values): {equivalent}")
assert equivalent, "pd.merge and SQL JOIN diverged!"
print("✅ SQL JOIN and pd.merge produce identical output.")

==============================================================================
SQL JOIN vs pd.merge — side by side
==============================================================================

SQL JOIN result (first 10):

        category_name                                                        title  rating  price_gbp  price_inr  in_stock
0            Classics                                    The Story of Hong Gildong       4      43.19    4556.54         1
1            Classics                               Little Women (Little Women #1)       4      28.07    2961.38         1
2            Classics  The Complete Stories and Poems (The Works of Edgar Allan...       4      26.78    2825.29         1
3            Classics                                            The Secret Garden       4      15.08    1590.94         1
4  Historical Fiction                      A Flight of Arrows (The Pathfinders #2)       5      55.53    5858.42         1
5  Historical Fiction                                          While You Were Mine       5      41.32    4359.26         1
6  Historical Fiction                                                 The Red Tent       5      35.66    3762.13         1
7  Historical Fiction                                                 Mrs. Houdini       5      30.25    3191.38         1
8  Historical Fiction                                        The Passion of Dolssa       5      28.32    2987.76         1
9  Historical Fiction                                       Voyager (Outlander #3)       5      21.07    2222.89         1

pd.merge result (first 10):

   book_id                                                        title  price_gbp  price_inr  rating  in_stock  category_id       category_name
0      158                                    The Story of Hong Gildong      43.19    4556.54       4         1            1            Classics
1      149                               Little Women (Little Women #1)      28.07    2961.38       4         1            1            Classics
2      155  The Complete Stories and Poems (The Works of Edgar Allan...      26.78    2825.29       4         1            1            Classics
3      145                                            The Secret Garden      15.08    1590.94       4         1            1            Classics
4       46                      A Flight of Arrows (The Pathfinders #2)      55.53    5858.42       5         1            2  Historical Fiction
5       65                                          While You Were Mine      41.32    4359.26       5         1            2  Historical Fiction
6       60                                                 The Red Tent      35.66    3762.13       5         1            2  Historical Fiction
7       48                                                 Mrs. Houdini      30.25    3191.38       5         1            2  Historical Fiction
8       57                                        The Passion of Dolssa      28.32    2987.76       5         1            2  Historical Fiction
9       59                                       Voyager (Outlander #3)      21.07    2222.89       5         1            2  Historical Fiction

Equivalent (same columns, same order, same values): True
✅ SQL JOIN and pd.merge produce identical output.